cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'

urlpatterns = [
    path('export/', views.export, name='export'),
    path('product-bulk-upload/', views.product_bulk_upload, name='product-bulk-upload'),
    path('vehicle-bulk-upload/', views.vehicle_bulk_upload, name='vehicle-bulk-upload'),
    path('product-image-upload/', views.product_image_upload, name='product-image-upload'),
    path('post-feedback/', views.add_feedback, name='post-feedback'),
    path('get-sales-and-featured-product/', views.get_sales_and_featured_product, name='get-sales-and-featured-product'),
    path('get-company-social-links/', views.get_company_social_links, name='get-company-social-links'),
    path('get-deals-banner/', views.get_deals_banner, name='get-deals-banner'),
    path('export-delivered-orders/<str:order_status>/', views.ExportOrderView.as_view(), name='export_order'),
]

cms/templates/empty_query.html
{% extends "admin/base_site.html" %} {% block content %}
<h1>Export</h1>
<div class="alert alert-warning" role="alert">{{ message }}</div>
{% endblock %}

cms/templates/error.html
{% extends "admin/base_site.html" %}
{% block content %}
<h1 >Error 🚫</h1>
    <div style="display: flex; align-items: center; gap: 0.3rem;">
        <p>Incorrect format uploaded!!! <a href="{% url 'admin:index' %}">Home page</a></p>
        
    </div>
  </form>
{% endblock %}

cms/templates/export.html
{% extends "admin/base_site.html" %} {% block content %}
<h1>Export</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div style="display: flex; flex-direction: column; gap: 1rem;">
    <a style="text-decoration: underline; font-weight: 400; font-size: 12px;" href="{% url 'cms:export_order' 'D' %}">📄 Export DELIVERED orders</a>
    <a style="text-decoration: underline; font-weight: 400; font-size: 12px;" href="{% url 'cms:export_order' 'C' %}">📄 Export CANCELLED orders</a>
    <a style="text-decoration: underline; font-weight: 400; font-size: 12px;" href="{% url 'cms:export_order' 'I' %}">📄 Export IN-PROGRESS orders</a>
    <a style="text-decoration: underline; font-weight: 400; font-size: 12px;" href="{% url 'cms:export_order' 'S' %}">📄 Export SHIPPED orders</a>
  </div>
</form>
{% endblock %}

cms/templates/index.html
{% extends "admin/base_site.html" %} {% block content %}
<h1>Upload Product CSV</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit" style="background-color: #417690; color: white; height: 35px; width: 80px; border: none; cursor: pointer">Upload</button>
</form>
{% endblock %}

cms/templates/upload_complete.html
{% extends "admin/base_site.html" %}
{% block content %}
  <h1>Upload Completed ✅</h1>
    <div style="display: flex; align-items: center; gap: 0.3rem;">
        <p>You can return to the <a href="{% url 'admin:index' %}">Home page</a></p>
        
    </div>
  </form>
{% endblock %}

cms/templates/upload_image.html
{% extends "admin/base_site.html" %} {% load static %} {% block content %}
<head>
  <style>
    .row {
      display: grid;
      grid-template-columns: repeat(18, 1fr);
      grid-gap: 0.8rem;
      flex-direction: row;
    }

    img {
      width: 50px;
      height: 50px;
      border: 2px solid gray;
      padding: 5px;
    }

    img:hover {
      box-shadow: 0 0 2px 1px rgba(0, 0, 0, 0.5);
    }

    ul {
      list-style:disc;
    }

    button {
        background-color: #b8daf3;
        color: #496f8b;
        border: none;
        width: 70px;
        border-radius: 20px;
        height: 20px;
        font-size: 12px;
    }
  </style>
</head>
<h1>Upload Product Image</h1>
<form method="post" enctype="multipart/form-data" multiple>
  {% csrf_token %} {{ form.as_p }}
  <button type="submit", style="background-color: #417690; color: white; height: 35px; width: 80px; border: none; cursor: pointer;">Upload</button>
</form>

<ul>
  {% for url in new_image %}
    <li>
      <script src="{% static 'main.js' %}"></script>
      <img src="{{ url }}" />
      <button
        onclick="copyLink( '{{ url }} ', '{{ forloop.counter }}' )"
        id="{{ forloop.counter }}"
      >
        copy link
      </button>
    </li>
  {% endfor %}
</ul>

<br />
<br />

<div class="container">
  <br />
  <br />
  <h1>Uploaded Images</h1>
  <div class="row">
    {% for image in images %}
    <div class="col-md-4 mb-3">
      <div class="card">
        <script src="{% static 'main.js' %}"></script>
        <img
          onclick="copyLink( '{{ image }} ', '{{ image.id }}')"
          id="{{image.id }}"
          src="{{ image }}"
          class="card-img-top"
        />
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

cms/templates/upload_image_complete.html
{% extends "admin/base_site.html" %} {% load static %} 
{% block content %}
{% if new_image %}
    <ul>
        {% for url in new_image %}
            <li>
                <h1>Image{{ forloop.counter }} uploaded</h1>
                <script src="{% static 'main.js' %}"></script>
                <button onclick="copyLink( '{{ url }} ', '{{ forloop.counter }}' )" id="{{ forloop.counter }}">copy link</button>
            </li>
        {% endfor %}

    </ul>
{% else %}
    <h1>No Image Uploaded</h1>
{% endif %}

{% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.min.js"></script>
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.min.css"
/>

cms/templates/vehicle_bulk_upload.html
{% extends "admin/base_site.html" %}
{% block content %}
  <h1>Upload Vehicle CSV</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" style="background-color: #417690; color: white; height: 35px; width: 80px; border: none; cursor: pointer;">Upload</button>
  </form>
{% endblock %}